version: "3.8"

services:
  php:
    image: php:8.2-fpm
    container_name: test-php
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    container_name: test-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php