name: CI/CD for Docker with PHP and Nginx

# Event-Trigger, um den Workflow bei einem Push auf den main-Branch auszulösen
on:
  [push]:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Der Workflow läuft auf einem Ubuntu-Runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  

      - name: Build Docker containers
        run: |
          docker-compose -f docker-compose.yaml build 

      - name: Run Docker containers
        run: |
          docker-compose up -d

      
