name: CI/CD for Docker with PHP and Nginx

# Event-Trigger, um den Workflow bei einem Push auf den main-Branch auszulösen
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Der Workflow läuft auf einem Ubuntu-Runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  

      - name: Build Docker containers
        run: |
          docker build .
          
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      

      - name: Run Docker containers
        run: |
          docker-compose up -d

      
